---
title: "Emmer Green Station"
author: "https://github.com/nikhouri/station"
output:
  html_document:
    fig_width: 10
    fig_height: 4
    toc: TRUE
---
Generated `r format(Sys.time(),"%F %T",tz='UTC',usetz=TRUE)`

```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, }
library(knitr)

# Number format function
numfmt <- function(x) format(x, big.mark="\U00A0", decimal.mark=".", scientific=FALSE)

# RDB query
url <- 'http://localhost:5011/.csv?'
query <- 'pctile:{ y (100 xrank y:asc y) bin x}; select last time, now:last data, low:pctile[5;data], high:pctile[95;data] by sym,units from obs where host=`garden,sym in `temperature`humidity`pressure'
uquery <- URLencode(query)
dfn <- read.csv(paste0(url,uquery),stringsAsFactors=FALSE)
dfn$now <- numfmt(round(dfn$now,1))
dfn$low <- numfmt(round(dfn$low,1))
dfn$high <- numfmt(round(dfn$high,1))
dfn$time = as.POSIXct(dfn$time,format='0D%H:%M:%S',tz='UTC')
colnames(dfn) <- c("Variable","Units","Timestamp (UTC)","Last","Min (5th%)","Max (95th%)")

knitr::kable(dfn)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, }
library(ggplot2)

# RDB query
url <- 'http://localhost:5011/.csv?'
query <- 'pctile:{ y (100 xrank y:asc y) bin x}; select low:pctile[5;data], median:med data, high:pctile[95;data] by date:.z.d,10 xbar time.minute,sym from obs where host=`garden'
uquery <- URLencode(query)
today <- read.csv(paste0(url,uquery),stringsAsFactors=FALSE)
today$time = as.POSIXct(today$minute,format='%H:%M',tz='UTC')
today$day <- 'today'

# HDB query
url <- 'http://localhost:5012/.csv?'
query <- 'pctile:{ y (100 xrank y:asc y) bin x}; select low:pctile[5;data], median:med data, high:pctile[95;data] by date,10 xbar time.minute,sym from obs where host=`garden,date=.z.d-1'
uquery <- URLencode(query)
yday <- read.csv(paste0(url,uquery),stringsAsFactors=FALSE)
yday$time = as.POSIXct(yday$minute,format='%H:%M',tz='UTC')
yday$day <- 'yesterday'

# Join queries
dfr <- rbind(today,yday)

# Tol Vibrant colour map
tolvibrant <- c("#EE3377", "#EE7733", "#0077BB", "#009988", "#33BBEE", "#CC3311", "#BBBBBB")

# Temperature chart
ggplot(dfr[dfr$sym=='temperature',]) +
  # Data series
  geom_line(aes(x=time,y=median,color=day), size=1) +
  geom_ribbon(aes(x=time,ymin=low,ymax=high,fill=day), alpha=0.2) + 
  # Axis scales and colour scales
  scale_y_continuous(label=numfmt) +
  scale_color_discrete(type=tolvibrant) +
  scale_fill_discrete(type=tolvibrant) +
  # Plot labels
  labs(title="Air Temperature",
       x=NULL, y="°C",
       subtitle = "10 minute medians and 5th/95th percentiles",
       color=NULL,fill=NULL) +
  # Themeing & fonts
  theme_light() +
  theme(legend.position="top",
        text=element_text(size=15, family="Fira Sans Extra Condensed"),
        plot.title=element_text(family="Fira Sans Extra Condensed Medium"),
        plot.caption=element_text(color="#666666"))

# Humidity chart
ggplot(dfr[dfr$sym=='humidity',]) +
  # Data series
  geom_line(aes(x=time,y=median,color=day), size=1) +
  geom_ribbon(aes(x=time,ymin=low,ymax=high,fill=day), alpha=0.2) + 
  # Axis scales and colour scales
  scale_y_continuous(label=numfmt) +
  scale_color_discrete(type=tolvibrant) +
  scale_fill_discrete(type=tolvibrant) +
  # Plot labels
  labs(title="Humidity",
       x=NULL, y="Percent",
       subtitle = "10 minute medians and 5th/95th percentiles",
       color=NULL,fill=NULL) +
  # Themeing & fonts
  theme_light() +
  theme(legend.position="top",
        text=element_text(size=15, family="Fira Sans Extra Condensed"),
        plot.title=element_text(family="Fira Sans Extra Condensed Medium"),
        plot.caption=element_text(color="#666666"))

# Air pressure chart
ggplot(dfr[dfr$sym=='pressure',]) +
  # Data series
  geom_line(aes(x=time,y=median,color=day), size=1) +
  geom_ribbon(aes(x=time,ymin=low,ymax=high,fill=day), alpha=0.2) + 
  # Axis scales and colour scales
  scale_y_continuous(label=numfmt) +
  scale_color_discrete(type=tolvibrant) +
  scale_fill_discrete(type=tolvibrant) +
  # Plot labels
  labs(title="Air Pressure",
       x=NULL, y="hPa",
       subtitle = "10 minute medians and 5th/95th percentiles",
       color=NULL,fill=NULL) +
  # Themeing & fonts
  theme_light() +
  theme(legend.position="top",
        text=element_text(size=15, family="Fira Sans Extra Condensed"),
        plot.title=element_text(family="Fira Sans Extra Condensed Medium"),
        plot.caption=element_text(color="#666666"))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, fig.width=10, fig.height=6}
ggplot(today[today$sym %in% c('cpu','cputemp','mem'),]) +
  # Data series
  geom_line(aes(x=time,y=median,color=sym), size=1) +
  geom_ribbon(aes(x=time,ymin=low,ymax=high,fill=sym), alpha=0.2) + 
  # Axis scales and colour scales
  scale_y_continuous(label=numfmt)+
  scale_color_discrete(type=tolvibrant) +
  scale_fill_discrete(type=tolvibrant) +
  # Plot labels
  labs(title="Weather Station Diagnostics",
       x=NULL, y="CPU %, Mem %, CPU °C",
       subtitle = "Today, 10 minute medians and 5th/95th percentiles",
       color=NULL,fill=NULL) +
  # Themeing & fonts
  theme_light() +
  theme(legend.position="top",
        text=element_text(size=15, family="Fira Sans Extra Condensed"),
        plot.title=element_text(family="Fira Sans Extra Condensed Medium"),
        plot.caption=element_text(color="#666666"))
```
